- web/src/SecureVote/Components/UI/FullPageSlide.elm
- web/src/SecureVote/SPAs/SwarmMVP/Ballot.elm
- web/src/SecureVote/SPAs/SwarmMVP/DialogTypes.elm
- web/src/SecureVote/SPAs/SwarmMVP/Helpers.elm
- web/src/SecureVote/SPAs/SwarmMVP/Model.elm
- web/src/SecureVote/SPAs/SwarmMVP/Msg.elm
- web/src/SecureVote/SPAs/SwarmMVP/Routes.elm
- web/src/SecureVote/SPAs/SwarmMVP/Views/DialogV.elm
> Allow rich HTML in dialogs without storing html in state

- elm-package.json
- web/src/SecureVote/Components/UI/Dialog.elm
- web/src/SecureVote/SPAs/SwarmMVP/Ballot.elm
- web/src/SecureVote/SPAs/SwarmMVP/DialogTypes.elm
- web/src/SecureVote/SPAs/SwarmMVP/Main.elm
- web/src/SecureVote/SPAs/SwarmMVP/Views/SwmCastVoteV.elm
resolve #84
Also add some init config stuff (setting fields)
> Add longer descriptions for ballot options

- web/src/SecureVote/SPAs/SwarmMVP/Model.elm
- web/src/SecureVote/SPAs/SwarmMVP/Msg.elm
- web/src/SecureVote/SPAs/SwarmMVP/Update.elm
- web/src/SecureVote/SPAs/SwarmMVP/Views/RootV.elm
- web/src/SecureVote/SPAs/SwarmMVP/Views/SwmVotingV.elm
I added toasts to `LogErr` messages but I noticed there was some more error stuff in `Helpers.elm`
Also, I'm not sure if everything I added to `Update.elm` is necessary, I tried to refactor out as much of the stuff that we don't need as I could.
> Add toasts for error messages to resolve #67

- tests/ChecksumTests.elm
I think there were some other cases that you wanted to test for weren't there @XertroV ?
> Add tests for ethereum address checksum to resolve #31

- web/src/SecureVote/SPAs/SwarmMVP/Routes.elm
- web/src/SecureVote/SPAs/SwarmMVP/Views/RootV.elm
- web/src/SecureVote/SPAs/SwarmMVP/Views/SwmCastVoteV.elm
- web/src/SecureVote/SPAs/SwarmMVP/Views/SwmDelegateV.elm
> Add delegate view

- web/src/SecureVote/Components/UI/Dialog.elm
- web/src/SecureVote/SPAs/SwarmMVP/Views/DialogV.elm
Not really sure what you want here exactly, but how's this?
> Add geth dialog boilerplate

- web/src/SecureVote/Components/UI/Btn.elm
- web/src/SecureVote/SPAs/SwarmMVP/Views/SwmVotingV.elm
How do we test this @XertroV ?
> Add MEW link generation

- web/src/SecureVote/SPAs/SwarmMVP/Views/SwmVotingV.elm
> Add real ballot summary data

- web/css/cssload-spinner.css
- web/index.ejs
- web/index.js
- web/src/SecureVote/SPAs/SwarmMVP/Model.elm
- web/src/SecureVote/SPAs/SwarmMVP/Views/SwmVotingV.elm
> Add loading spinner for elm loading and for ballot encryption

- web/src/SecureVote/SPAs/SwarmMVP/Views/DialogV.elm
- web/src/SecureVote/SPAs/SwarmMVP/Views/SwmDelegateV.elm
> Add some copy explaining delegation

- web/src/SecureVote/Components/UI/Dialog.elm
- web/src/SecureVote/Components/UI/FullPageSlide.elm
- web/src/SecureVote/Eth/Web3.elm
- web/src/SecureVote/Eth/Web3.ts
- web/src/SecureVote/SPAs/SwarmMVP/Ballot.elm
- web/src/SecureVote/SPAs/SwarmMVP/Main.elm
- web/src/SecureVote/SPAs/SwarmMVP/Model.elm
- web/src/SecureVote/SPAs/SwarmMVP/Msg.elm
- web/src/SecureVote/SPAs/SwarmMVP/Routes.elm
- web/src/SecureVote/SPAs/SwarmMVP/Update.elm
- web/src/SecureVote/SPAs/SwarmMVP/Views/OpeningSlideV.elm
- web/src/SecureVote/SPAs/SwarmMVP/Views/RootV.elm
- web/src/SecureVote/SPAs/SwarmMVP/Views/SwmDelegateV.elm
- web/src/SecureVote/SPAs/SwarmMVP/Web3Handler.elm
> Opening slide + ballot verification

- bin/solidity/compile.sh
- web/src/SecureVote/SPAs/SwarmMVP/Const.elm
- also remove optimize-runs in compiler for solidity
> Add production contract addr

- BallotVerification.md
- elm-package.json
- web/src/SecureVote/Components/UI/Dialog.elm
- web/src/SecureVote/Eth/Web3.ts
- web/src/SecureVote/SPAs/SwarmMVP/Helpers.elm
- web/src/SecureVote/SPAs/SwarmMVP/Main.elm
- web/src/SecureVote/SPAs/SwarmMVP/Model.elm
- web/src/SecureVote/SPAs/SwarmMVP/Msg.elm
- web/src/SecureVote/SPAs/SwarmMVP/Routes.elm
- web/src/SecureVote/SPAs/SwarmMVP/Update.elm
- web/src/SecureVote/SPAs/SwarmMVP/Views/DialogV.elm
- web/src/SecureVote/SPAs/SwarmMVP/Views/OpeningSlideV.elm
- web/src/SecureVote/SPAs/SwarmMVP/Views/SwmVotingV.elm
- web/src/SecureVote/SPAs/SwarmMVP/Web3Handler.elm
resolve #160 
resolve #159 
resolve #157 
resolve #156 
resolve #153 
resolve #141 
resolve #139
> Final polish

- .travis.yml
- contract/test/swmVotingMVP.js
- package.json
- web/_redirects
- web/index.ejs
- web/src/SecureVote/Eth/Web3.elm
- web/src/SecureVote/Eth/Web3.ts
- web/src/SecureVote/SPAs/SwarmMVP/Helpers.elm
- web/src/SecureVote/SPAs/SwarmMVP/Types.elm
- web/src/SecureVote/SPAs/SwarmMVP/Update.elm
- web/src/SecureVote/SPAs/SwarmMVP/Views/DialogV.elm
- web/src/SecureVote/SPAs/SwarmMVP/Views/OpeningSlideV.elm
- web/src/SecureVote/SPAs/SwarmMVP/Views/SwmVotingV.elm
- webpack.config.js
- yarn.lock
resolve #170 
resolve #66 
resolve #172
> add redirects and remove responsive meta tag

- BallotVerification.md
> Add full ballot verification instructions

- bin/solidity/deploy.js
- bower.json
- contract/contracts/Erc20.sol
- package.json
- pureSrc/SecureVote/Democs/SwarmMVP/Auditor.purs
- pureSrc/SecureVote/Democs/SwarmMVP/Ballot.purs
- pureSrc/SecureVote/Democs/SwarmMVP/BallotContract.js
- pureSrc/SecureVote/Democs/SwarmMVP/BallotContract.purs
- pureSrc/SecureVote/Utils/ArrayBuffer.purs
- pureSrc/SecureVote/Utils/Decimal.js
- pureSrc/SecureVote/Utils/Decimal.purs
- pureSrc/SecureVote/Utils/Numbers.purs
- pureSrc/SecureVote/Utils/String.purs
- pureTest/SV/CompleteCycle.purs
- yarn.lock
- Add Utils.Decimal for `toFixed`
- Refactor to use Decimal where relevant
- Add some formatting for results
- Ensure arbitrary props returned from contracts are `String`s
resolve #144
> Implement using Decimal for count

- pureSrc/SecureVote/Democs/SwarmMVP/Auditor.purs
- pureSrc/SecureVote/Democs/SwarmMVP/BallotContract.js
- pureSrc/SecureVote/Democs/SwarmMVP/BallotContract.purs
- pureSrc/SecureVote/Utils/String.purs
> Pull down release schedule params and print with results

- pureSrc/SecureVote/Democs/SwarmMVP/Auditor.purs
- pureSrc/SecureVote/Democs/SwarmMVP/BallotContract.js
- pureSrc/SecureVote/Democs/SwarmMVP/BallotContract.purs
- pureSrc/SecureVote/Democs/SwarmMVP/Const.purs
- pureTest/SV/CompleteCycle.purs
> Implement getting balance at a particular block

- TestKeys.md
- build_prod.sh
- elm-package.json
- package.json
- pureSrc/SecureVote/Democs/SwarmMVP/AuditApp.purs
- pureSrc/SecureVote/Democs/SwarmMVP/BallotContract.purs
- web/index.ejs
- web/src/SecureVote/Eth/Utils.elm
- web/src/SecureVote/Eth/Web3.elm
- web/src/SecureVote/Eth/Web3.js
- web/src/SecureVote/SPAs/SwarmMVP/Ballot.elm
- web/src/SecureVote/SPAs/SwarmMVP/Ballots/DevBasicBallot.elm
- web/src/SecureVote/SPAs/SwarmMVP/Ballots/ReleaseSchedule.elm
- web/src/SecureVote/SPAs/SwarmMVP/Ballots/Types.elm
- web/src/SecureVote/SPAs/SwarmMVP/Msg.elm
- web/src/SecureVote/SPAs/SwarmMVP/Update.elm
- web/src/SecureVote/SPAs/SwarmMVP/Views/BallotOpeningSlideV.elm
- web/src/SecureVote/SPAs/SwarmMVP/Views/CastVoteV.elm
- web/src/SecureVote/SPAs/SwarmMVP/Views/HowToVoteV.elm
- web/src/SecureVote/SPAs/SwarmMVP/Web3Handler.elm
* Add discussion link when needed
* Add new SWM ballots to dev for testing (see http://develop--sv-mirror-swarm-mvp.netlify.com/)
* fix metamask bug if we give it an address that doens't exist in the wallet
* speed up auditor slightly
* Polish
> Merge polish changes into master

- web/src/SecureVote/SPAs/SwarmMVP/Views/VotingV.elm
> All v2 changes to date (note dev-v2 was branched from v2-remote-data)

- package.json
- web/admin.js
- web/index.js
- web/js/web3Stuff.js
- web/src/SecureVote/Ballots/SpecSource.js
- web/src/SecureVote/Eth/Web3.js
- web/src/SecureVote/SPAs/SwarmMVP/Model.elm
- web/src/SecureVote/SPAs/SwarmMVP/Update.elm
- web/src/SecureVote/SPAs/SwarmMVP/Views/CastVoteV.elm
- web/src/SecureVote/SPAs/SwarmMVP/Views/DialogV.elm
- web/src/SecureVote/SPAs/SwarmMVP/Views/VotingV.elm
- yarn.lock
- fix results time
- implement backup source via S3 / archive
- fix MEW instructions
- fix validation instructions
- little UI improvement
> fix ui v2 issues

- pureSrc/SV/Light/AuditBallot.purs
- web/src/SecureVote/Components/UI/RenderAudit.elm
- web/src/SecureVote/Eth/Types.elm
- web/src/SecureVote/Eth/Web3.elm
- also handle "warn" msg from auditor
> Handle correct dlgt timing (end of ballot)
